In [1]:
import pandas as pd
import numpy as np

# part 1

## 시리즈

In [57]:
# series
dict_data = {'a' : 1, 'b' : 2, 'c' : 3}
sr = pd.Series(dict_data)
print(type(sr)) # sr의 자료형 출력
sr


<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64

In [3]:
student = ['진슬', '2000-01-30', 'female']
sr = pd.Series(student, index = ['이름', '생년월일', '성별'])
print(type(sr))
sr

<class 'pandas.core.series.Series'>


이름              진슬
생년월일    2000-01-30
성별          female
dtype: object

In [4]:
sr[1:]

생년월일    2000-01-30
성별          female
dtype: object

In [5]:
print(sr.index)
sr.values

Index(['이름', '생년월일', '성별'], dtype='object')


array(['진슬', '2000-01-30', 'female'], dtype=object)

In [7]:
sr['이름']

'진슬'

## 데이터프레임

In [25]:
data = [[4, 5, 6], [7, 8, 9], [10, 11, 12]]
df2 = pd.DataFrame(data, index = ['a', 'b', 'c'], columns = ['d', 'e', 'f'])
df2

d   e   f
a   4   5   6
b   7   8   9
c  10  11  12

In [41]:
df2.index = ['k', 'l', 'k'] # 행 인덱스 변경
df2.columns = ['h', 'o', 'p'] # 열 인덱스 변경
df2

h   o   p
k   4   5   6
l   7   8   9
k  10  11  12

In [42]:
df2 = df2.rename(index = {'l' : 'n'}, columns = {'h' : 'm'}) # 일부 행, 열 인덱스 변경
df2

m   o   p
k   4   5   6
n   7   8   9
k  10  11  12

In [43]:
k_drop = df2.drop('k', axis = 0)
k_drop

m  o  p
n  7  8  9

In [44]:
col_drop = df2.drop(['o', 'm'], axis = 1)
col_drop

p
k   6
n   9
k  12

In [46]:
# dataframe
exam = {'이름' : ['서준', '우현', '인아'],
       '수학' : [90, 80, 70],
       '영어' : [85, 95, 100],
       '체육' : [100, 90, 90]}
df = pd.DataFrame(exam)
df

이름  수학   영어   체육
0  서준  90   85  100
1  우현  80   95   90
2  인아  70  100   90

In [47]:
# '이름'열을 행 인덱스로 지정
df = df.set_index('이름')
df

수학   영어   체육
이름              
서준  90   85  100
우현  80   95   90
인아  70  100   90

In [48]:
print(df.index)
print(df.columns)

Index(['서준', '우현', '인아'], dtype='object', name='이름')
Index(['수학', '영어', '체육'], dtype='object')


In [49]:
df.loc['서준']

수학     90
영어     85
체육    100
Name: 서준, dtype: int64

In [57]:
df.loc['서준' : '인아']

수학   영어   체육
이름              
서준  90   85  100
우현  80   95   90
인아  70  100   90

In [58]:
df.iloc[0:2]

수학  영어   체육
이름             
서준  90  85  100
우현  80  95   90

In [66]:
df[['수학', '체육']]

수학   체육
이름         
서준  90  100
우현  80   90
인아  70   90

In [71]:
df.loc[['서준'], ['수학', '영어']]

수학  영어
이름        
서준  90  85

In [73]:
df.iloc[[0], [0, 1]]

수학  영어
이름        
서준  90  85

In [61]:
df.수학

이름
서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [74]:
df['과학'] = [30, 40, 50]
df

수학   영어   체육  과학
이름                  
서준  90   85  100  30
우현  80   95   90  40
인아  70  100   90  50

In [107]:
exam = {'이름' : ['서준', '우현', '인아'],
       '수학' : [90, 80, 70],
       '영어' : [85, 95, 100],
       '체육' : [100, 90, 90]}
df2 = pd.DataFrame(exam)
df2

이름  수학   영어   체육
0  서준  90   85  100
1  우현  80   95   90
2  인아  70  100   90

In [108]:
df2.loc['행4'] = 50
df2

이름  수학   영어   체육
0   서준  90   85  100
1   우현  80   95   90
2   인아  70  100   90
행4  50  50   50   50

In [77]:
df2.loc[0, ['수학', '영어']] = 80
df2

이름  수학   영어   체육
0   서준  80   80  100
1   우현  80   95   90
2   인아  70  100   90
행4  50  50   50   50

In [109]:
df2.iloc[[0, 1], 2:] = 50
df2

이름  수학   영어  체육
0   서준  90   50  50
1   우현  80   50  50
2   인아  70  100  90
행4  50  50   50  50

In [110]:
df2.loc[[2,'행4']][['수학', '영어']]

수학   영어
2   70  100
행4  50   50

In [112]:
df2.loc[[2,'행4']][['수학', '영어']] = 20
df2

이름  수학   영어  체육
0   서준  90   50  50
1   우현  80   50  50
2   인아  70  100  90
행4  50  50   50  50

## 인덱스 활용

In [118]:
a = np.arange(16).reshape(4, 4)

In [119]:
a.shape

(4, 4)

In [120]:
data = pd.DataFrame(a, index = ['Ohio', 'Colorado', 'Utah', 'New York'], columns = ['one', 'two', 'three', 'four'])

In [121]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [22]:
# 'three'가 5보다 큰 도시의 데이터만 선택하기
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [132]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [133]:
data[data<5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [134]:
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
# 5보다 작은 값은 0으로 채우기
data < 5
data[data < 5]
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [30]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
[a > 5]

[array([False, False, False, False, False,  True,  True,  True,  True])]

In [34]:
a = np.array([3, 1, 5, 9])
a.sort()
a

array([1, 3, 5, 9])

In [39]:
a = np.array([3, 1, 9, 5])
b = a.argsort()[::-1]
b

array([2, 3, 0, 1], dtype=int64)

In [41]:
a = np.arange(1, 10)
b = a.reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
c = b[[0, 1], 2]
c

array([3, 6])

In [56]:
name = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score = np.array([78, 95, 84, 98, 88])
data = np.vstack([name, score]).reshape(2, 5).T
data

array([['John', '78'],
       ['Mike', '95'],
       ['Sarah', '84'],
       ['Kate', '98'],
       ['Samuel', '88']], dtype='<U11')

In [62]:
sort_index = data[:,1].argsort()
sort_index

array([0, 2, 4, 1, 3], dtype=int64)

In [63]:
sort_data = data[sort_index]
sort_data

array([['John', '78'],
       ['Sarah', '84'],
       ['Samuel', '88'],
       ['Mike', '95'],
       ['Kate', '98']], dtype='<U11')

In [136]:
titanic_df = pd.read_csv('titanic_train.csv')

In [137]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [141]:
titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [75]:
titanic_df[titanic_df['Age'] > 60][['Name', 'Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [76]:
titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [144]:
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'
titanic_df.loc[cond1 & cond2 & cond3]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [77]:
# 나이가 60세 이상이고, 선실 등급이 1등급이며, 성별이 여성인 승객 추출
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'
titanic_df.loc[cond1 & cond2 & cond3]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

## index 활용

In [146]:
exam_data = {'이름' : ['서준', '우현', '인아'],
            '수학' : [90, 80, 70],
            '영어' : [98, 89, 95],
            '음악' : [85, 95, 100],
            '체육' : [100, 90, 90]}
df = pd.DataFrame(exam_data)
print(df)
# 특정 열 행 인덱스로 설정
df1 = df.set_index(['이름'])
print(df1)

# 멀티 인덱스
mul_df = df.set_index(['수학', '음악'])
print(mul_df)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
    수학  영어   음악   체육
이름                  
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
        이름  영어   체육
수학 음악              
90 85   서준  98  100
80 95   우현  89   90
70 100  인아  95   90


In [150]:
dict_data = {'c0' : [1, 2, 3], 'c1' : [4, 5, 6], 'c2' : [7, 8, 9]}
df = pd.DataFrame(dict_data, index = ['r0', 'r1', 'r2'])
print(df)
# 행 인덱스 재배열 
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
df2 = df.reindex(new_index)
print(df2) # 기존 df에 존재하지 않은 행 인덱스가 새로 추가될 경우 그 값은 NaN값이 입력됨.
# 따라서 만일 유효한 값으로 채우려면 fill_value옵션을 이용한다.
df3 = df.reindex(new_index, fill_value = 0)
print(df3)

    c0  c1  c2
r0   1   4   7
r1   2   5   8
r2   3   6   9
     c0   c1   c2
r0  1.0  4.0  7.0
r1  2.0  5.0  8.0
r2  3.0  6.0  9.0
r3  NaN  NaN  NaN
r4  NaN  NaN  NaN
    c0  c1  c2
r0   1   4   7
r1   2   5   8
r2   3   6   9
r3   0   0   0
r4   0   0   0


In [151]:
# 행 인덱스 초기화
df3.reset_index()

index  c0  c1  c2
0    r0   1   4   7
1    r1   2   5   8
2    r2   3   6   9
3    r3   0   0   0
4    r4   0   0   0

In [153]:
df3.index

Index(['r0', 'r1', 'r2', 'r3', 'r4'], dtype='object')

In [156]:
# 행 인덱스 기준으로 정렬
df3.index = ['a', 'b', 'c', 'd', 'e'] # 행 인덱스명 변경
print(df3)
df3.sort_index(ascending = False) # 내림차순 정렬

   c0  c1  c2
a   1   4   7
b   2   5   8
c   3   6   9
d   0   0   0
e   0   0   0


c0  c1  c2
e   0   0   0
d   0   0   0
c   3   6   9
b   2   5   8
a   1   4   7

In [158]:
# 특정 열(c1)을 기준으로 내림차순 정렬
print(df3)
df3.sort_values(by = 'c1', ascending = False)

   c0  c1  c2
a   1   4   7
b   2   5   8
c   3   6   9
d   0   0   0
e   0   0   0


c0  c1  c2
c   3   6   9
b   2   5   8
a   1   4   7
d   0   0   0
e   0   0   0

### 시리즈 연산

In [165]:
# nan값이 없는 시리즈 끼리 연산
sr1 = pd.Series({'국어' : 100, '영어': 80, '수학' : 90})
sr2 = pd.Series({'수학' : 80, '국어' : 90, '영어' : 80})
add = sr1 + sr2
diff = sr1 - sr2
mul = sr1 * sr2
div = sr1 / sr2
pd.DataFrame([add, diff, mul, div], index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])


국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [166]:
# nan값이 있을 경우(혹은 동일한 인덱스가 없을 경우) 시리즈 연산
sr1 = pd.Series({'국어' : np.nan, '영어': 80, '수학' : 90})
sr2 = pd.Series({'수학' : 80, '국어' : 90, '영어' : 80, '과학' : 70})
add = sr1 + sr2
diff = sr1 - sr2
mul = sr1 * sr2
div = sr1 / sr2
pd.DataFrame([add, diff, mul, div], index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])


과학  국어        수학      영어
덧셈  NaN NaN   170.000   160.0
뺄셈  NaN NaN    10.000     0.0
곱셈  NaN NaN  7200.000  6400.0
나눗셈 NaN NaN     1.125     1.0

In [168]:
# nan가 있을 경우 fill_value를 통해 0으로 채워주기
sr1 = pd.Series({'국어' : np.nan, '영어': 80, '수학' : 90})
sr2 = pd.Series({'수학' : 80, '국어' : 90, '영어' : 80, '과학' : 70})
print(sr1)
print(sr2)
add = sr1.add(sr2, fill_value = 0)
diff = sr1.sub(sr2, fill_value = 0)
mul = sr1.mul(sr2, fill_value = 0)
div = sr1.div(sr2, fill_value = 0)
pd.DataFrame([add, diff, mul, div], index = ['덧셈', '뺄셈', '곱셈', '나눗셈'])


국어     NaN
영어    80.0
수학    90.0
dtype: float64
수학    80
국어    90
영어    80
과학    70
dtype: int64


과학    국어        수학      영어
덧셈   70.0  90.0   170.000   160.0
뺄셈  -70.0 -90.0    10.000     0.0
곱셈    0.0   0.0  7200.000  6400.0
나눗셈   0.0   0.0     1.125     1.0

## PART 3 : 데이터 확인하기

In [171]:
# df 기본정보
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [173]:
# 각 열의 자료형
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [177]:
titanic_df.shape

(891, 12)

In [174]:
# 각 열의 데이터 개수
titanic_df.count() # 시리즈 형태

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [178]:
# 각 열의 고유값 개수
print(titanic_df['Pclass'].value_counts())
# NaN값 제외하고 고유값 세기
titanic_df['Pclass'].value_counts(dropna = True)

3    491
1    216
2    184
Name: Pclass, dtype: int64


3    491
1    216
2    184
Name: Pclass, dtype: int64

### 통계함수 적용 : mean, median, max, min, std, corr 등

In [182]:
# 평균
print(titanic_df.mean())
# 특정 열 평균
titanic_df[['Age', 'Fare']].mean()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64


Age     29.699118
Fare    32.204208
dtype: float64

In [183]:
# 상관계수
titanic_df.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [184]:
# Age와 Survived 상관계수
titanic_df[['Age', 'Survived']].corr() # -0.07이다.

Age  Survived
Age       1.000000 -0.077221
Survived -0.077221  1.000000